version: '3.8'

services:
  homepage:
    build: .
    container_name: homepage
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - default
      - monitoring-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`homepage.home.local`)"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.services.homepage.loadbalancer.server.port=80"
      - "traefik.docker.network=monitoring-network"

networks:
  monitoring-network:
    external: true
